module.exports = {
    PermissionsText: {
        CreateInstantInvite: "Create Instant Invite",
        KickMembers: "Kick Members",
        BanMembers: "Ban Members",
        Administrator: "Administrator",
        ManageChannels: "Manage Channels",
        ManageGuild: "Manage Guild",
        AddReactions: "Add Reactions",
        ViewAuditLog: "View Audit Log",
        PrioritySpeaker: "Priority Speaker",
        Stream: "Stream",
        ViewChannel: "View Channel",
        SendMessages: "Send Messages",
        SendTTSMessages: "Send TTS Messages",
        ManageMessages: "Manage Messages",
        EmbedLinks: "Embed Links",
        AttachFiles: "Attach Files",
        ReadMessageHistory: "Ready Message History",
        MentionEveryone: "Mention Everyone",
        UseExternalEmojis: "Use External Emojis",
        ViewGuildInsights: "View Guild Insights",
        Connect: "Connect",
        Speak: "Speak",
        MuteMembers: "Mute Members",
        DeafenMembers: "Deafen Members",
        MoveMembers: "Move Members",
        UseVAD: "Use Voice Activity",
        ChangeNickname: "Change Nickname",
        ManageNicknames: "Manage Nicknames",
        ManageRoles: "Manage Roles",
        ManageWebhooks: "Manage Webhooks",
        ManageEmojisAndStickers: "Manage Emojis and Stickers",
        UseApplicationCommands: "Use Application Commands",
        RequestToSpeak: "Request to Speak",
        ManageEvents: "Manage Events",
        ManageThreads: "Manage Threads",
        CreatePublicThreads: "Create Public Threads",
        CreatePrivateThreads: "Create Private Threads",
        UseExternalStickers: "Use External Stickers",
        SendMessagesInThreads: "Send Messages in Threads",
        UseEmbeddedActivities: "Use Embedded Activities",
        ModerateMembers: "Moderate Members"
    }
}